-- Highlight definitions for rose-pine highlight_groups.
-- Consumes the palette table; returns a highlight_groups map.

local p = require("theme.palette")

return {
  -- Base UI
  Normal = { fg = p.fg, bg = p.bg },
  NormalNC = { fg = p.fg, bg = p.bg },
  NormalFloat = { fg = p.fg, bg = p.bg },
  FloatBorder = { fg = p.rose, bg = p.bg },
  FloatTitle = { fg = p.rose, bg = p.bg },
  EndOfBuffer = { fg = p.overlay, bg = p.bg },
  SignColumn = { bg = p.bg },
  FoldColumn = { bg = p.bg },
  ColorColumn = { bg = p.overlay },
  CursorLine = { bg = p.surface },
  CursorLineNr = { fg = p.rose, bg = p.bg },
  LineNr = { fg = p.dim, bg = p.gutter },
  WinSeparator = { fg = p.faint, bg = p.bg },
  VertSplit = { fg = p.faint, bg = p.bg },
  StatusLine = { fg = p.fg, bg = p.overlay },
  StatusLineNC = { fg = p.dim, bg = p.bg },
  WinBar = { fg = p.dim, bg = p.bg },
  WinBarNC = { fg = p.dim, bg = p.bg },
  TabLine = { fg = p.dim, bg = p.bg },
  TabLineSel = { fg = p.rose, bg = p.overlay },
  TabLineFill = { bg = p.bg },
  Pmenu = { fg = p.fg, bg = p.overlay },
  PmenuSel = { fg = p.bg, bg = p.rose },
  PmenuSbar = { bg = p.overlay },
  PmenuThumb = { bg = p.rose },
  Visual = { bg = p.visual },
  Search = { fg = p.bg, bg = p.pine, bold = true },
  IncSearch = { fg = p.bg, bg = p.rose },
  MatchParen = { fg = p.rose_bright, bold = true },
  Directory = { fg = p.rose },
  Title = { fg = p.rose, bold = true },
  NonText = { fg = p.overlay },
  SpecialKey = { fg = p.overlay },

  -- Syntax: Logic tier (vivid pink, bold for keywords)
  Keyword = { fg = p.rose, bold = true },
  Statement = { fg = p.rose, bold = true },
  Function = { fg = p.rose },
  Tag = { fg = p.rose },
  Define = { fg = p.rose },
  PreProc = { fg = p.rose_hot },
  Include = { fg = p.rose_hot },

  -- Syntax: Data tier (pastel rose — soft pink for literals)
  Constant = { fg = p.rose_bright },
  String = { fg = p.rose_bright, italic = true },
  Character = { fg = p.rose_bright },
  Number = { fg = p.rose_bright },
  Float = { fg = p.rose_bright },
  Boolean = { fg = p.rose_bright, bold = true },
  Macro = { fg = p.rose_bright },
  Special = { fg = p.rose_bright },

  -- Syntax: Text tier (lavender-white — neutral body)
  Identifier = { fg = p.fg },
  Operator = { fg = p.fg },
  Type = { fg = p.iris },
  Delimiter = { fg = p.dim },

  -- Syntax: Receded tier (muted — comments pushed back)
  Comment = { fg = p.dim, italic = true },
  Todo = { fg = p.bg, bg = p.rose, bold = true },
  Error = { fg = p.error },

  -- Treesitter
  ["@variable"] = { fg = p.fg },
  ["@variable.builtin"] = { fg = p.iris, italic = true },
  ["@variable.parameter"] = { fg = p.fg },
  ["@constant"] = { fg = p.rose_bright },
  ["@constant.builtin"] = { fg = p.rose_bright, bold = true },
  ["@module"] = { fg = p.iris },
  ["@label"] = { fg = p.rose },
  ["@string"] = { fg = p.rose_bright, italic = true },
  ["@string.escape"] = { fg = p.rose },
  ["@character"] = { fg = p.rose_bright },
  ["@number"] = { fg = p.rose_bright },
  ["@boolean"] = { fg = p.rose_bright, bold = true },
  ["@float"] = { fg = p.rose_bright },
  ["@function"] = { fg = p.rose },
  ["@function.builtin"] = { fg = p.rose, italic = true },
  ["@function.call"] = { fg = p.fn_call },
  ["@function.macro"] = { fg = p.rose_bright },
  ["@method"] = { fg = p.rose },
  ["@method.call"] = { fg = p.fn_call },
  ["@keyword"] = { fg = p.rose, bold = true },
  ["@keyword.return"] = { fg = p.rose, bold = true },
  ["@keyword.function"] = { fg = p.rose, bold = true },
  ["@keyword.operator"] = { fg = p.rose },
  ["@keyword.conditional"] = { fg = p.rose, bold = true },
  ["@keyword.repeat"] = { fg = p.rose, bold = true },
  ["@keyword.import"] = { fg = p.rose_hot },
  ["@keyword.directive"] = { fg = p.rose_hot },
  ["@keyword.storage"] = { fg = p.rose },
  ["@type"] = { fg = p.iris },
  ["@type.builtin"] = { fg = p.iris, bold = true },
  ["@type.qualifier"] = { fg = p.iris },
  ["@operator"] = { fg = p.fg },
  ["@punctuation"] = { fg = p.dim },
  ["@punctuation.bracket"] = { fg = p.dim },
  ["@punctuation.delimiter"] = { fg = p.dim },
  ["@punctuation.special"] = { fg = p.rose },
  ["@comment"] = { fg = p.dim, italic = true },
  ["@tag"] = { fg = p.rose },
  ["@tag.attribute"] = { fg = p.iris },
  ["@tag.delimiter"] = { fg = p.dim },
  ["@property"] = { fg = p.fg },
  ["@parameter"] = { fg = p.fg },
  ["@constructor"] = { fg = p.iris },
  ["@namespace"] = { fg = p.iris },
  ["@include"] = { fg = p.rose_hot },
  ["@field"] = { fg = p.fg },

  -- LSP semantic tokens
  ["@lsp.type.class"] = { fg = p.iris },
  ["@lsp.type.struct"] = { fg = p.iris },
  ["@lsp.type.enum"] = { fg = p.iris },
  ["@lsp.type.interface"] = { fg = p.iris },
  ["@lsp.type.namespace"] = { fg = p.iris },
  ["@lsp.type.function"] = { fg = p.fn_call },
  ["@lsp.type.method"] = { fg = p.fn_call },
  ["@lsp.type.macro"] = { fg = p.rose_bright },
  ["@lsp.type.parameter"] = { fg = p.fg },
  ["@lsp.type.property"] = { fg = p.fg },
  ["@lsp.type.variable"] = { fg = p.fg },
  ["@lsp.type.type"] = { fg = p.iris },
  ["@lsp.type.typeParameter"] = { fg = p.iris },
  ["@lsp.type.keyword"] = { fg = p.rose, bold = true },

  -- Diagnostics
  DiagnosticError = { fg = p.error },
  DiagnosticWarn = { fg = p.warn },
  DiagnosticInfo = { fg = p.info },
  DiagnosticHint = { fg = p.hint },
  DiagnosticVirtualTextError = { fg = p.error, bg = p.bg },
  DiagnosticVirtualTextWarn = { fg = p.warn, bg = p.bg },
  DiagnosticVirtualTextInfo = { fg = p.info, bg = p.bg },
  DiagnosticVirtualTextHint = { fg = p.hint, bg = p.bg },
  DiagnosticUnderlineError = { sp = p.error, undercurl = true },
  DiagnosticUnderlineWarn = { sp = p.warn, undercurl = true },

  -- Git signs
  GitSignsAdd = { fg = p.git_add },
  GitSignsChange = { fg = p.git_change },
  GitSignsDelete = { fg = p.git_delete },

  -- NeoTree
  NeoTreeNormal = { fg = p.fg, bg = p.bg },
  NeoTreeNormalNC = { fg = p.fg, bg = p.bg },
  NeoTreeEndOfBuffer = { bg = p.bg },
  NeoTreeDirectoryName = { fg = p.rose },
  NeoTreeDirectoryIcon = { fg = p.rose },
  NeoTreeFileName = { fg = p.fg },
  NeoTreeGitModified = { fg = p.git_change },
  NeoTreeGitAdded = { fg = p.git_add },
  NeoTreeGitDeleted = { fg = p.git_delete },
  NeoTreeGitUntracked = { fg = p.rose_bright },
  NeoTreeIndentMarker = { fg = p.faint },
  NeoTreeRootName = { fg = p.rose, bold = true },
  NeoTreeWinSeparator = { fg = p.faint, bg = p.bg },

  -- Telescope
  TelescopeBorder = { fg = p.rose, bg = p.bg },
  TelescopeTitle = { fg = p.rose },
  TelescopePromptNormal = { bg = p.bg },
  TelescopeResultsNormal = { bg = p.bg },
  TelescopePreviewNormal = { bg = p.bg },
  TelescopeSelection = { bg = p.overlay, fg = p.rose },

  -- Indent guides
  IblIndent = { fg = p.faint },
  IblScope = { fg = p.rose },

  -- Which-key
  WhichKey = { fg = p.rose },
  WhichKeyGroup = { fg = p.iris },
  WhichKeyDesc = { fg = p.fg },
  WhichKeySeparator = { fg = p.dim },

  -- Notify
  NotifyBackground = { bg = p.bg },
}
